user_config: null

dataset:
  path: null
  split_file: null
  split_name: test
  session_label: "01"
  space: "MNI152"

  roots: null

outputs:
  pred_root: null
  pred_roots: null
  out_dir: ./outputs/eval

eval:
  seed: 1234
  pred_desc: "deform"
  device: "cuda:0"
  n_chamfer: 150000
  n_assd_hd: 150000
  log_level: "INFO"

hydra:
  run:
    dir: ${outputs.out_dir}
  output_subdir: null
  job:
    chdir: false
