user_config: null

dataset:
  path: null
  split_file: null
  split_name: test
  session_label: "01"
  space: "MNI152"
  roots: null



  surface_name: ["lh_pial", "lh_white", "rh_pial", "rh_white"]
  use_probability_map: false
  use_fixed_initial_surface: true
  fixed_template_root: null
  prob_clip_min: 0.0
  prob_clip_max: 1.0
  prob_gamma: 1.0

inference:
  device: "cuda:0"
  batch_size: 1
  num_workers: 0
  log_level: "INFO"
  overwrite: true

model:
  ckpt_path: null
  strict_load: true
  c_in: 1
  sigma: 1
  n_steps: 8
  inshape: [184, 224, 184]
  c_hid: [8, 16, 32, 64, 128, 128]
  gn_groups: 8
  dropout: 0.1

outputs:
  out_root: null
  out_roots: null

  log_dir: ./outputs/inference_logs
